<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Cores {
			
		private $id;
		private $cor;
		private $hexadecimal;
		private $cadastrado;
		private $modificado;
		private $tipo_cor;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setCor($cor) {
			$this->cor = $cor;
		}
		
		public function getCor() {
			return $this->cor;
		}
					
		public function setHexadecimal($hexadecimal) {
			$this->hexadecimal = $hexadecimal;
		}
		
		public function getHexadecimal() {
			return $this->hexadecimal;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setTipo_cor($tipo_cor) {
			$this->tipo_cor = $tipo_cor;
		}
		
		public function getTipo_cor() {
			return $this->tipo_cor;
		}
					
	}
	
?>