<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Menu_submenus {
			
		private $id;
		private $menu_submenu;
		private $link;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $menu;
		private $situacao_registro;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setMenu_submenu($menu_submenu) {
			$this->menu_submenu = $menu_submenu;
		}
		
		public function getMenu_submenu() {
			return $this->menu_submenu;
		}
					
		public function setLink($link) {
			$this->link = $link;
		}
		
		public function getLink() {
			return $this->link;
		}
					
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
		
		public function getOrdem() {
			return $this->ordem;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setMenu($menu) {
			$this->menu = $menu;
		}
		
		public function getMenu() {
			return $this->menu;
		}
					
		public function setSituacao_registro($situacao_registro) {
			$this->situacao_registro = $situacao_registro;
		}
		
		public function getSituacao_registro() {
			return $this->situacao_registro;
		}
					
	}
	
?>