<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Token implements \JsonSerializable {
			
		private $usuario;
		private $cpf;
		private $foto;
		
		public function __construct($object = null) { 
			if ($object != null) {
				if (isset($object->usuario)) {
					$this->usuario = $object->usuario;
				}
				if (isset($object->cpf)) {
					$this->cpf = $object->cpf;
				}
				if (isset($object->foto)) {
					$this->foto = $object->foto;
				}
			}
		}

		public function getUsuario() {
			return $this->usuario;
		}
		
		public function setUsuario($usuario) {
			$this->usuario = $usuario;
		}
	
		public function getCpf() {
			return $this->cpf;
		}
		
		public function setCpf($cpf) {
			$this->cpf = $cpf;
		}
		
		public function getFoto() {
			return $this->foto;
		}
		
		public function setFoto($foto) {
			$this->foto = $foto;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}
		
	}
	
?>