<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class Unidade_colaboradoresDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO unidade_colaboradores (
				unidade_colaborador
				, cpf
				, cadastrado
				, modificado
				, unidade
				, unidade_cargo
				) VALUES";
				
		public $read = 
				"unidade_colaboradores.id AS \"unidade_colaboradores.id\"
				, unidade_colaboradores.unidade_colaborador AS \"unidade_colaboradores.unidade_colaborador\"
				, unidade_colaboradores.cpf AS \"unidade_colaboradores.cpf\"
				, unidade_colaboradores.cadastrado AS \"unidade_colaboradores.cadastrado\"
				, unidade_colaboradores.modificado AS \"unidade_colaboradores.modificado\"
				, unidade_colaboradores.unidade AS \"unidade_colaboradores.unidade\"
				, unidade_colaboradores.unidade_cargo AS \"unidade_colaboradores.unidade_cargo\"
				";
				
		private $update = "UPDATE unidade_colaboradores SET";
		private $delete = "DELETE FROM unidade_colaboradores";
		
		public $from = "unidade_colaboradores unidade_colaboradores";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Unidade_colaboradores}unidade_colaboradores
		 */
		public function setCreate($unidade_colaboradores) {		
			$this->sql = $this->create . " (\"" . 
					$unidade_colaboradores->getUnidade_colaborador() .
					"\", \"" . $unidade_colaboradores->getCpf() .
					"\", \"" . $unidade_colaboradores->getCadastrado() .
					"\", \"" . $unidade_colaboradores->getModificado() .
					"\", \"" . $unidade_colaboradores->getUnidade() .
					"\", \"" . $unidade_colaboradores->getUnidade_cargo() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$unidadesDao = new model\UnidadesDao($this->connection);
			$unidade_cargosDao = new model\Unidade_cargosDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $unidadesDao->read . ", " . $unidade_cargosDao->read . 
					" FROM " . $this->getFrom() .", " . $unidadesDao->from . ", " . $unidade_cargosDao->from . 
					($this->getWhere() == "" ? " WHERE unidade_colaboradores.unidade = unidades.id AND unidade_colaboradores.unidade_cargo = unidade_cargos.id" : $this->getWhere()) . 
					" AND unidade_colaboradores.unidade = unidades.id AND unidade_colaboradores.unidade_cargo = unidade_cargos.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Unidade_colaboradores}unidade_colaboradores  
		 * @param {String} where
		 */
		public function setUpdate($unidade_colaboradores, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $unidade_colaboradores->getId() . 
					"\", unidade_colaborador = \"" . $unidade_colaboradores->getUnidade_colaborador() . 
					"\", cpf = \"" . $unidade_colaboradores->getCpf() . 
					"\", modificado = \"" . $unidade_colaboradores->getModificado() . 
					"\", unidade = \"" . $unidade_colaboradores->getUnidade() . 
					"\", unidade_cargo = \"" . $unidade_colaboradores->getUnidade_cargo() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"unidade_colaboradores.size\" from unidade_colaboradores" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "unidade_colaboradores.size", $row["unidade_colaboradores.size"]);
				
				$pages = ceil($row["unidade_colaboradores.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "unidade_colaboradores.page", $this->connection->getPosition());
				$this->setResponse(0, "unidade_colaboradores.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "unidade_colaboradores.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Unidade_colaboradores} unidade_colaboradores 
		 * @return {Boolean}
		 */
		public function create($unidade_colaboradores) {
			$result = "";

			$this->setCreate($unidade_colaboradores);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "unidade_colaboradores.id", $row["unidade_colaboradores.id"]);
				$this->setResponse($line, "unidade_colaboradores.unidade_colaborador", $row["unidade_colaboradores.unidade_colaborador"]);
				$this->setResponse($line, "unidade_colaboradores.unidade_colaborador.format.json", modelDoubleQuotesJson($row["unidade_colaboradores.unidade_colaborador"]));
				$this->setResponse($line, "unidade_colaboradores.unidade_colaborador.format", modelDoubleQuotes($row["unidade_colaboradores.unidade_colaborador"]));
				$this->setResponse($line, "unidade_colaboradores.unidade_colaborador.view", addLine($row["unidade_colaboradores.unidade_colaborador"]));
				$this->setResponse($line, "unidade_colaboradores.cpf", $row["unidade_colaboradores.cpf"]);
				$this->setResponse($line, "unidade_colaboradores.cadastrado", modelDateTime($row["unidade_colaboradores.cadastrado"]));
				$this->setResponse($line, "unidade_colaboradores.modificado", modelDateTime($row["unidade_colaboradores.modificado"]));
				$this->setResponse($line, "unidade_colaboradores.unidade", $row["unidade_colaboradores.unidade"]);
				$this->setResponse($line, "unidades.unidade", $row["unidades.unidade"]);
				$this->setResponse($line, "unidade_colaboradores.unidade_cargo", $row["unidade_colaboradores.unidade_cargo"]);
				$this->setResponse($line, "unidade_cargos.unidade_cargo", $row["unidade_cargos.unidade_cargo"]);
			
				$this->setResponse($line, "unidade_colaboradores.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Unidade_colaboradores} unidade_colaboradores 
		 * @return {Boolean}
		 */
		public function update($unidade_colaboradores) {
			$result = "";
			
			$this->setUpdate($unidade_colaboradores, "unidade_colaboradores.id = " . $unidade_colaboradores->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "unidade_colaboradores.id", $row["unidade_colaboradores.id"]);
				$this->setResponse($size, "unidade_colaboradores.unidade_colaborador", $row["unidade_colaboradores.unidade_colaborador"]);
			
				if ($row["unidade_colaboradores.id"] == $selected)
					$this->setResponse($size, "unidade_colaboradores.selected", "selected");
				else
					$this->setResponse($size, "unidade_colaboradores.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "unidade_colaboradores.id", $row["unidade_colaboradores.id"]);
				$this->setResponse($size, "unidade_colaboradores.unidade_colaborador", $row["unidade_colaboradores.unidade_colaborador"]);
				$this->setResponse($size, "unidade_colaboradores.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>