<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class UnidadesDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO unidades (
				unidade
				, cadastrado
				, modificado
				, situacao_registro
				) VALUES";
				
		public $read = 
				"unidades.id AS \"unidades.id\"
				, unidades.unidade AS \"unidades.unidade\"
				, unidades.cadastrado AS \"unidades.cadastrado\"
				, unidades.modificado AS \"unidades.modificado\"
				, unidades.situacao_registro AS \"unidades.situacao_registro\"
				";
				
		private $update = "UPDATE unidades SET";
		private $delete = "DELETE FROM unidades";
		
		public $from = "unidades unidades";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Unidades}unidades
		 */
		public function setCreate($unidades) {		
			$this->sql = $this->create . " (\"" . 
					$unidades->getUnidade() .
					"\", \"" . $unidades->getCadastrado() .
					"\", \"" . $unidades->getModificado() .
					"\", \"" . $unidades->getSituacao_registro() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$situacoes_registrosDao = new model\Situacoes_registrosDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $situacoes_registrosDao->read . 
					" FROM " . $this->getFrom() .", " . $situacoes_registrosDao->from . 
					($this->getWhere() == "" ? " WHERE unidades.situacao_registro = situacoes_registros.id" : $this->getWhere()) . 
					" AND unidades.situacao_registro = situacoes_registros.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Unidades}unidades  
		 * @param {String} where
		 */
		public function setUpdate($unidades, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $unidades->getId() . 
					"\", unidade = \"" . $unidades->getUnidade() . 
					"\", modificado = \"" . $unidades->getModificado() . 
					"\", situacao_registro = \"" . $unidades->getSituacao_registro() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"unidades.size\" from unidades" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "unidades.size", $row["unidades.size"]);
				
				$pages = ceil($row["unidades.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "unidades.page", $this->connection->getPosition());
				$this->setResponse(0, "unidades.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "unidades.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Unidades} unidades 
		 * @return {Boolean}
		 */
		public function create($unidades) {
			$result = "";

			$this->setCreate($unidades);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "unidades.id", $row["unidades.id"]);
				$this->setResponse($line, "unidades.unidade", $row["unidades.unidade"]);
				$this->setResponse($line, "unidades.unidade.format.json", modelDoubleQuotesJson($row["unidades.unidade"]));
				$this->setResponse($line, "unidades.unidade.format", modelDoubleQuotes($row["unidades.unidade"]));
				$this->setResponse($line, "unidades.unidade.view", addLine($row["unidades.unidade"]));
				$this->setResponse($line, "unidades.cadastrado", modelDateTime($row["unidades.cadastrado"]));
				$this->setResponse($line, "unidades.modificado", modelDateTime($row["unidades.modificado"]));
				$this->setResponse($line, "unidades.situacao_registro", $row["unidades.situacao_registro"]);
				$this->setResponse($line, "situacoes_registros.situacao_registro", $row["situacoes_registros.situacao_registro"]);
			
				$this->setResponse($line, "unidades.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Unidades} unidades 
		 * @return {Boolean}
		 */
		public function update($unidades) {
			$result = "";
			
			$this->setUpdate($unidades, "unidades.id = " . $unidades->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "unidades.id", $row["unidades.id"]);
				$this->setResponse($size, "unidades.unidade", $row["unidades.unidade"]);
			
				if ($row["unidades.id"] == $selected)
					$this->setResponse($size, "unidades.selected", "selected");
				else
					$this->setResponse($size, "unidades.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "unidades.id", $row["unidades.id"]);
				$this->setResponse($size, "unidades.unidade", $row["unidades.unidade"]);
				$this->setResponse($size, "unidades.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>