<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class Unidade_plantao_unidade_colaboradorDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO unidade_plantao_unidade_colaborador (
				hora_inicial
				, hora_final
				, cadastrado
				, modificado
				, unidade_plantao
				, unidade_colaborador
				) VALUES";
				
		public $read = 
				"unidade_plantao_unidade_colaborador.id AS \"unidade_plantao_unidade_colaborador.id\"
				, unidade_plantao_unidade_colaborador.hora_inicial AS \"unidade_plantao_unidade_colaborador.hora_inicial\"
				, unidade_plantao_unidade_colaborador.hora_final AS \"unidade_plantao_unidade_colaborador.hora_final\"
				, unidade_plantao_unidade_colaborador.cadastrado AS \"unidade_plantao_unidade_colaborador.cadastrado\"
				, unidade_plantao_unidade_colaborador.modificado AS \"unidade_plantao_unidade_colaborador.modificado\"
				, unidade_plantao_unidade_colaborador.unidade_plantao AS \"unidade_plantao_unidade_colaborador.unidade_plantao\"
				, unidade_plantao_unidade_colaborador.unidade_colaborador AS \"unidade_plantao_unidade_colaborador.unidade_colaborador\"
				";
				
		private $update = "UPDATE unidade_plantao_unidade_colaborador SET";
		private $delete = "DELETE FROM unidade_plantao_unidade_colaborador";
		
		public $from = "unidade_plantao_unidade_colaborador unidade_plantao_unidade_colaborador";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Unidade_plantao_unidade_colaborador}unidade_plantao_unidade_colaborador
		 */
		public function setCreate($unidade_plantao_unidade_colaborador) {		
			$this->sql = $this->create . " (\"" . 
					$unidade_plantao_unidade_colaborador->getHora_inicial() .
					"\", \"" . $unidade_plantao_unidade_colaborador->getHora_final() .
					"\", \"" . $unidade_plantao_unidade_colaborador->getCadastrado() .
					"\", \"" . $unidade_plantao_unidade_colaborador->getModificado() .
					"\", \"" . $unidade_plantao_unidade_colaborador->getUnidade_plantao() .
					"\", \"" . $unidade_plantao_unidade_colaborador->getUnidade_colaborador() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$unidade_plantoesDao = new model\Unidade_plantoesDao($this->connection);
			$unidade_colaboradoresDao = new model\Unidade_colaboradoresDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $unidade_plantoesDao->read . ", " . $unidade_colaboradoresDao->read . 
					" FROM " . $this->getFrom() .", " . $unidade_plantoesDao->from . ", " . $unidade_colaboradoresDao->from . 
					($this->getWhere() == "" ? " WHERE unidade_plantao_unidade_colaborador.unidade_plantao = unidade_plantoes.id AND unidade_plantao_unidade_colaborador.unidade_colaborador = unidade_colaboradores.id" : $this->getWhere()) . 
					" AND unidade_plantao_unidade_colaborador.unidade_plantao = unidade_plantoes.id AND unidade_plantao_unidade_colaborador.unidade_colaborador = unidade_colaboradores.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Unidade_plantao_unidade_colaborador}unidade_plantao_unidade_colaborador  
		 * @param {String} where
		 */
		public function setUpdate($unidade_plantao_unidade_colaborador, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $unidade_plantao_unidade_colaborador->getId() . 
					"\", hora_inicial = \"" . $unidade_plantao_unidade_colaborador->getHora_inicial() . 
					"\", hora_final = \"" . $unidade_plantao_unidade_colaborador->getHora_final() . 
					"\", modificado = \"" . $unidade_plantao_unidade_colaborador->getModificado() . 
					"\", unidade_plantao = \"" . $unidade_plantao_unidade_colaborador->getUnidade_plantao() . 
					"\", unidade_colaborador = \"" . $unidade_plantao_unidade_colaborador->getUnidade_colaborador() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"unidade_plantao_unidade_colaborador.size\" from unidade_plantao_unidade_colaborador" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "unidade_plantao_unidade_colaborador.size", $row["unidade_plantao_unidade_colaborador.size"]);
				
				$pages = ceil($row["unidade_plantao_unidade_colaborador.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "unidade_plantao_unidade_colaborador.page", $this->connection->getPosition());
				$this->setResponse(0, "unidade_plantao_unidade_colaborador.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "unidade_plantao_unidade_colaborador.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Unidade_plantao_unidade_colaborador} unidade_plantao_unidade_colaborador 
		 * @return {Boolean}
		 */
		public function create($unidade_plantao_unidade_colaborador) {
			$result = "";

			$this->setCreate($unidade_plantao_unidade_colaborador);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.id", $row["unidade_plantao_unidade_colaborador.id"]);
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.hora_inicial", modelDateTime($row["unidade_plantao_unidade_colaborador.hora_inicial"]));
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.hora_final", modelDateTime($row["unidade_plantao_unidade_colaborador.hora_final"]));
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.cadastrado", modelDateTime($row["unidade_plantao_unidade_colaborador.cadastrado"]));
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.modificado", modelDateTime($row["unidade_plantao_unidade_colaborador.modificado"]));
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.unidade_plantao", $row["unidade_plantao_unidade_colaborador.unidade_plantao"]);
				$this->setResponse($line, "unidade_plantoes.unidade", $row["unidade_plantoes.unidade"]);
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.unidade_colaborador", $row["unidade_plantao_unidade_colaborador.unidade_colaborador"]);
				$this->setResponse($line, "unidade_colaboradores.unidade_colaborador", $row["unidade_colaboradores.unidade_colaborador"]);
			
				$this->setResponse($line, "unidade_plantao_unidade_colaborador.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Unidade_plantao_unidade_colaborador} unidade_plantao_unidade_colaborador 
		 * @return {Boolean}
		 */
		public function update($unidade_plantao_unidade_colaborador) {
			$result = "";
			
			$this->setUpdate($unidade_plantao_unidade_colaborador, "unidade_plantao_unidade_colaborador.id = " . $unidade_plantao_unidade_colaborador->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "unidade_plantao_unidade_colaborador.id", $row["unidade_plantao_unidade_colaborador.id"]);
				$this->setResponse($size, "unidade_plantao_unidade_colaborador.hora_inicial", $row["unidade_plantao_unidade_colaborador.hora_inicial"]);
			
				if ($row["unidade_plantao_unidade_colaborador.id"] == $selected)
					$this->setResponse($size, "unidade_plantao_unidade_colaborador.selected", "selected");
				else
					$this->setResponse($size, "unidade_plantao_unidade_colaborador.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "unidade_plantao_unidade_colaborador.id", $row["unidade_plantao_unidade_colaborador.id"]);
				$this->setResponse($size, "unidade_plantao_unidade_colaborador.hora_inicial", $row["unidade_plantao_unidade_colaborador.hora_inicial"]);
				$this->setResponse($size, "unidade_plantao_unidade_colaborador.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>