<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Unidade_plantao_unidade_colaborador {
			
		private $id;
		private $hora_inicial;
		private $hora_final;
		private $cadastrado;
		private $modificado;
		private $unidade_plantao;
		private $unidade_colaborador;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setHora_inicial($hora_inicial) {
			$this->hora_inicial = $hora_inicial;
		}
		
		public function getHora_inicial() {
			return $this->hora_inicial;
		}
					
		public function setHora_final($hora_final) {
			$this->hora_final = $hora_final;
		}
		
		public function getHora_final() {
			return $this->hora_final;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setUnidade_plantao($unidade_plantao) {
			$this->unidade_plantao = $unidade_plantao;
		}
		
		public function getUnidade_plantao() {
			return $this->unidade_plantao;
		}
					
		public function setUnidade_colaborador($unidade_colaborador) {
			$this->unidade_colaborador = $unidade_colaborador;
		}
		
		public function getUnidade_colaborador() {
			return $this->unidade_colaborador;
		}
					
	}
	
?>