<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "menu_submenus.menu_submenu LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "menu_submenus.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "menu_submenus.menu_submenu = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
	
	if ($order != "") {
		$o = explode("<gz>", $order);
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = $o[0] . " " . $o[1];
		} else {
			$limit = $o[0] . " " . $o[1] . " LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
		}		
	} else {
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = "menu_submenus.ordem ASC";	
		} else {
			if ($position > 0 && $itensPerPage > 0) {
				$limit = "menu_submenus.ordem ASC LIMIT " . 
						(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
			}
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["menu_submenus"] = $daoFactory->getMenu_submenusDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["menu_submenus"][0]["menu_submenus.menu_submenu"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/menu_submenus.html" : "/html/menu_submenus.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$menu_submenus = new model\Menu_submenus();
			$menu_submenus->setMenu_submenu(logicNull($request["menu_submenus.menu_submenu"]));
			$menu_submenus->setLink(logicNull($request["menu_submenus.link"]));
			
			$menu_submenusDao = $daoFactory->getMenu_submenusDao()->read("", "menu_submenus.ordem DESC LIMIT 0, 1", false);
			$menu_submenus->setOrdem($menu_submenusDao[0]["menu_submenus.ordem"] + 1);
				
			$menu_submenus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setMenu($request["menu_submenus.menu"]);
			$menu_submenus->setSituacao_registro($request["menu_submenus.situacao_registro"]);
			
			$resultDao = $daoFactory->getMenu_submenusDao()->create($menu_submenus);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "menu_submenus.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$menu_submenus = $daoFactory->getMenu_submenusDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($menu_submenus);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$menu_submenus = new model\Menu_submenus();
			$menu_submenus->setId($request["menu_submenus.id"]);
			$menu_submenus->setMenu_submenu(logicNull($request["menu_submenus.menu_submenu"]));
			$menu_submenus->setLink(logicNull($request["menu_submenus.link"]));
			
			$where = "menu_submenus.id = " . $request["menu_submenus.id"];
			
			$daoFactory->beginTransaction();
			$menu_submenusDao = $daoFactory->getMenu_submenusDao()->read($where, "", false);
			$daoFactory->close();

			$menu_submenus->setOrdem($menu_submenusDao[0]["menu_submenus.ordem"]);
				
			$menu_submenus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setMenu($request["menu_submenus.menu"]);
			$menu_submenus->setSituacao_registro($request["menu_submenus.situacao_registro"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getMenu_submenusDao()->update($menu_submenus);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["menu_submenus.id"] = $daoFactory->prepare($request["menu_submenus.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["menu_submenus.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "menu_submenus.id = " . $lines[$i];
				
				$resultDao = $daoFactory->getMenu_submenusDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	else if ($method == "changeOrder") {		
		$result = true;
		$daoFactory->beginTransaction();
		$call = $daoFactory->getMenu_submenusDao()->read("menu_submenus.id = " . $form[0], "", false);
		$answer = $daoFactory->getMenu_submenusDao()->read("menu_submenus.id = " . $form[1], "", false);
		$menu_submenusDao = $daoFactory->getMenu_submenusDao()->read("menu_submenus.ordem >= " . $answer[0]["menu_submenus.ordem"], "", false);
		if (is_array($menu_submenusDao) && sizeof($menu_submenusDao) > 0) {
			for ($x = 0; $x < sizeof($menu_submenusDao); $x++) {
				$menu_submenus = new model\Menu_submenus();
				$menu_submenus->setId($menu_submenusDao[$x]["menu_submenus.id"]);
				$menu_submenus->setMenu_submenu(logicNull($menu_submenusDao[$x]["menu_submenus.menu_submenu"]));
			$menu_submenus->setLink(logicNull($menu_submenusDao[$x]["menu_submenus.link"]));
			
			$menu_submenus->setOrdem($menu_submenusDao[$x]["menu_submenus.ordem"] + 1);
				
			$menu_submenus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setMenu($menu_submenusDao[$x]["menu_submenus.menu"]);
			$menu_submenus->setSituacao_registro($menu_submenusDao[$x]["menu_submenus.situacao_registro"]);
			
				$resultDao = $daoFactory->getMenu_submenusDao()->update($menu_submenus);			
				$result = !$result ? false : (!$resultDao ? false : true);
			}
			$menu_submenus = new model\Menu_submenus();
			$menu_submenus->setId($call[0]["menu_submenus.id"]);
			$menu_submenus->setMenu_submenu(logicNull($call[0]["menu_submenus.menu_submenu"]));
			$menu_submenus->setLink(logicNull($call[0]["menu_submenus.link"]));
			
			$menu_submenus->setOrdem($answer[0]["menu_submenus.ordem"]);
				
			$menu_submenus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$menu_submenus->setMenu($call[0]["menu_submenus.menu"]);
			$menu_submenus->setSituacao_registro($call[0]["menu_submenus.situacao_registro"]);
			
			$resultDao = $daoFactory->getMenu_submenusDao()->update($menu_submenus);			
			$result = !$result ? false : (!$resultDao ? false : true);
		}
		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}
		$daoFactory->close();
		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["menus"] = $daoFactory->getMenusDao()->read("menus.tipo_menu = 1", "menus.id ASC", false);
					$response["situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menu_submenus/menu_submenusCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead" || $method == "stateReadAll") {
				if ($method == "stateReadAll") {
					$method = "stateRead";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["menu_submenus"] = $daoFactory->getMenu_submenusDao()->read($where, $limit, true);
					if (!is_array($response["menu_submenus"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menu_submenus/menu_submenusRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["menu_submenus"] = $daoFactory->getMenu_submenusDao()->read($where, "", true);
					$response["menu_submenus"][0]["menu_submenus.menus"] = $daoFactory->getMenusDao()->read("menus.tipo_menu = 1", "menus.id ASC", false);
					for ($x = 0; $x < sizeof($response["menu_submenus"][0]["menu_submenus.menus"]); $x++) {
						if ($response["menu_submenus"][0]["menu_submenus.menus"][$x]["menus.id"] == 
								$response["menu_submenus"][0]["menu_submenus.menu"]) {
							$response["menu_submenus"][0]["menu_submenus.menus"][$x]["menus.selected"] = "selected";
						}
					}
					$response["menu_submenus"][0]["menu_submenus.situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					for ($x = 0; $x < sizeof($response["menu_submenus"][0]["menu_submenus.situacoes_registros"]); $x++) {
						if ($response["menu_submenus"][0]["menu_submenus.situacoes_registros"][$x]["situacoes_registros.id"] == 
								$response["menu_submenus"][0]["menu_submenus.situacao_registro"]) {
							$response["menu_submenus"][0]["menu_submenus.situacoes_registros"][$x]["situacoes_registros.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menu_submenus/menu_submenusUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled" || $method == "stateCalledAll") {
				if ($method == "stateCalledAll") {
					$method = "stateCalled";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND menu_submenus.@_FOREIGN_KEY = " . $base;
					else 
						$where = "menu_submenus.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["menu_submenus"] = $daoFactory->getMenu_submenusDao()->read($where, $limit, true);
					if (!is_array($response["menu_submenus"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menu_submenus/menu_submenusCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND menu_submenus.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "menu_submenus.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "menu_submenus.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["menu_submenus"] = $daoFactory->getMenu_submenusDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menu_submenus/menu_submenusSCR.html", $response) . 
						"<size>" . (is_array($response["menu_submenus"]) ? $response["menu_submenus"][0]["menu_submenus.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "menu_submenus.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["menu_submenus"] = $daoFactory->getMenu_submenusDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menu_submenus/menu_submenusCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$menu_submenus = new model\Menu_submenus();
					$menu_submenus->setMenu_submenu(logicNull($form[0]));
					$menu_submenus->setLink(logicNull($form[1]));
					
					$daoFactory->beginTransaction();
					$menu_submenusDao = $daoFactory->getMenu_submenusDao()->read("", "menu_submenus.ordem DESC LIMIT 0, 1", false);
					$daoFactory->close();
						
					$menu_submenus->setOrdem($menu_submenusDao[0]["menu_submenus.ordem"] + 1);
						
					$menu_submenus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$menu_submenus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$menu_submenus->setMenu($form[2]);
					$menu_submenus->setSituacao_registro($form[3]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getMenu_submenusDao()->create($menu_submenus);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$menu_submenus = new model\Menu_submenus();
					$menu_submenus->setId($code);
					$menu_submenus->setMenu_submenu(logicNull($form[0]));
					$menu_submenus->setLink(logicNull($form[1]));
					
					$where = "menu_submenus.id = " . $code;
					
					$daoFactory->beginTransaction();
					$menu_submenusDao = $daoFactory->getMenu_submenusDao()->read($where, "", false);
					$daoFactory->close();
						
					$menu_submenus->setOrdem($menu_submenusDao[0]["menu_submenus.ordem"]);
						
					$menu_submenus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$menu_submenus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$menu_submenus->setMenu($form[2]);
					$menu_submenus->setSituacao_registro($form[3]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getMenu_submenusDao()->update($menu_submenus);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "menu_submenus.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getMenu_submenusDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>