<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\logic;
	use src\model;	 
	 
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");

	$limit = "noticias.id DESC";
	if ($position > 0 && $itensPerPage > 0) {
		$limit .= " LIMIT " . (($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
	}
	if ($method == "page") {
		$daoFactory->beginTransaction();
		$response["slides"] = $daoFactory->getSlidesDao()->read("slides.situacao_registro = 1", "slides.ordem ASC", true);
		for ($x = 0; $x < sizeof($response["slides"]); $x++) {
			if ($x == 0) {
				$response["slides"][$x]["slides.selected"] = "fill-circle";
			} else {
				$response["slides"][$x]["slides.selected"] = "empty-circle";
				$response["slides"][$x]["slides.display"] = "display: none;";
			}
		}
		$response["noticias"] = $daoFactory->getNoticiasDao()->read("noticias.situacao_registro = 1", $limit, true);
		$daoFactory->close();
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/portal.html", $response);
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}

?>